language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t razaqofficial/portfolio -f Dockerfile.dev .
script:
  - docker run -e CI=true razaqofficial/portfolio npm run test