language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t razaqofficial/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true razaqofficial/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-719381170469"
  bucket_path: "docker-react"
  access_key_id: 'AKIA2O7TVRES4HMCTKXI'
  secret_access_key: "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"
  on:
    branch: main