language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t razaqofficial/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true razaqofficial/docker-react npm run test